import { Colors } from "@/constants/styles/colorTheme";

export const emotionList = [
  // primary: love
  { name: "love", color: Colors.red },
  { name: "affection", color: Colors.red },
  { name: "adoration", color: Colors.red },
  { name: "fondness", color: Colors.red },
  { name: "liking", color: Colors.red },
  { name: "caring", color: Colors.red },
  { name: "tenderness", color: Colors.red },
  { name: "compassion", color: Colors.red },
  { name: "sentimentality", color: Colors.red },
  { name: "desire", color: Colors.red },
  { name: "passion", color: Colors.red },
  { name: "infatuation", color: Colors.red },
  { name: "longing", color: Colors.red },

  // primary: joy
  { name: "joy", color: Colors.green },
  { name: "cheerfulness", color: Colors.green },
  { name: "amusement", color: Colors.green },
  { name: "bliss", color: Colors.green },
  { name: "gaiety", color: Colors.green },
  { name: "delight", color: Colors.green },
  { name: "enjoyment", color: Colors.green },
  { name: "gladness", color: Colors.green },
  { name: "happiness", color: Colors.green },
  { name: "jubilation", color: Colors.green },
  { name: "satisfaction", color: Colors.green },
  { name: "euphoria", color: Colors.green },
  { name: "zest", color: Colors.green },
  { name: "enthusiasm", color: Colors.green },
  { name: "zeal", color: Colors.green },
  { name: "excitement", color: Colors.green },
  { name: "contentment", color: Colors.green },
  { name: "pleasure", color: Colors.green },
  { name: "pride", color: Colors.green },
  { name: "triumph", color: Colors.green },
  { name: "optimism", color: Colors.green },
  { name: "eagerness", color: Colors.green },
  { name: "hope", color: Colors.green },
  { name: "enthrallment", color: Colors.green },
  { name: "relief", color: Colors.green },

  // primary: surprise
  { name: "surprise", color: Colors.mainBlue },
  { name: "amazement", color: Colors.mainBlue },
  { name: "astonishment", color: Colors.mainBlue },

  // primary: anger
  { name: "anger", color: Colors.orange },
  { name: "irritability", color: Colors.orange },
  { name: "aggravation", color: Colors.orange },
  { name: "annoyance", color: Colors.orange },
  { name: "frustration", color: Colors.orange },
  { name: "rage", color: Colors.orange },
  { name: "outrage", color: Colors.orange },
  { name: "hostility", color: Colors.orange },
  { name: "bitterness", color: Colors.orange },
  { name: "hatred", color: Colors.orange },
  { name: "dislike", color: Colors.orange },
  { name: "disgust", color: Colors.orange },
  { name: "revulsion", color: Colors.orange },
  { name: "contempt", color: Colors.orange },
  { name: "loathing", color: Colors.orange },
  { name: "envy", color: Colors.orange },
  { name: "jealousy", color: Colors.orange },
  { name: "torment", color: Colors.orange },

  // primary: sadness
  { name: "sadness", color: Colors.mainGray },
  { name: "suffering", color: Colors.mainGray },
  { name: "despair", color: Colors.mainGray },
  { name: "gloom", color: Colors.mainGray },
  { name: "unhappiness", color: Colors.mainGray },
  { name: "grief", color: Colors.mainGray },
  { name: "sorrow", color: Colors.mainGray },
  { name: "disappointment", color: Colors.mainGray },
  { name: "displeasure", color: Colors.mainGray },
  { name: "shame", color: Colors.mainGray },
  { name: "guilt", color: Colors.mainGray },
  { name: "regret", color: Colors.mainGray },
  { name: "remorse", color: Colors.mainGray },
  { name: "alienation", color: Colors.mainGray },
  { name: "embarrassment", color: Colors.mainGray },
  { name: "insecurity", color: Colors.mainGray },
  { name: "isolation", color: Colors.mainGray },
  { name: "loneliness", color: Colors.mainGray },
  { name: "rejection", color: Colors.mainGray },
  { name: "sympathy", color: Colors.mainGray },

  // primary: fear
  { name: "distress", color: Colors.purplePastel },
  { name: "fear", color: Colors.purplePastel },
  { name: "shock", color: Colors.purplePastel },
  { name: "fright", color: Colors.purplePastel },
  { name: "horror", color: Colors.purplePastel },
  { name: "panic", color: Colors.purplePastel },
  { name: "mortification", color: Colors.purplePastel },
  { name: "anxiety", color: Colors.purplePastel },
  { name: "suspense", color: Colors.purplePastel },
  { name: "apprehension", color: Colors.purplePastel },
  { name: "worry", color: Colors.purplePastel },
  { name: "dread", color: Colors.purplePastel },
];

export const moodValueTitles = [
  "terrible",
  "bad",
  "rather_bad",
  "average",
  "rather_good",
  "good",
  "very_good",
]; //1-7

export const emotionStrengthTitles = [
  "barely_noticable",
  "weak",
  "significant",
  "strong",
  "overwhealmingly_strong",
]; //1-5
