const emotionList = [
  { name: "Calm", color: "#aed581" },
  { name: "Relaxed", color: "#aed581" },
  { name: "Peaceful", color: "#aed581" },
  { name: "Serene", color: "#aed581" },
  { name: "Joyful", color: "#f38e4e" },
  { name: "Ecstatic", color: "#f38e4e" },
  { name: "Hopeful", color: "#f38e4e" },
  { name: "Optimistic", color: "#f38e4e" },
  { name: "Grateful", color: "#f38e4e" },
  { name: "Proud", color: "#d46a6a" },
  { name: "Satisfied", color: "#aed581" },
  { name: "Triumphant", color: "#d46a6a" },
  { name: "Capable", color: "#f38e4e" },
  { name: "Talented", color: "#f38e4e" },
  { name: "Loving", color: "#d46a6a" },
  { name: "Protected", color: "#aed581" },
  { name: "Respected", color: "#aed581" },
  { name: "Energized", color: "#f38e4e" },
  { name: "Motivated", color: "#f38e4e" },
  { name: "Curious", color: "#f38e4e" },
  { name: "Confused", color: "#b8b8b8" },
  { name: "Surprised", color: "#f38e4e" },
  { name: "Shocked", color: "#d46a6a" },
  { name: "Puzzled", color: "#b8b8b8" },
  { name: "Interested", color: "#f38e4e" },
  { name: "Baffled", color: "#b8b8b8" },
  { name: "Indecisive", color: "#b8b8b8" },
  { name: "Torn", color: "#b8b8b8" },
  { name: "Ambivalent", color: "#b8b8b8" },
  { name: "Hesitant", color: "#b8b8b8" },
  { name: "Stunned", color: "#b8b8b8" },
  { name: "Astonished", color: "#f38e4e" },
  { name: "Startled", color: "#d46a6a" },
  { name: "Overwhelmed", color: "#d46a6a" },
  { name: "Anxious", color: "#b8b8b8" },
  { name: "Fearful", color: "#b8b8b8" },
  { name: "Appalled", color: "#b8b8b8" },
  { name: "Repulsed", color: "#b8b8b8" },
  { name: "Upset", color: "#d46a6a" },
  { name: "Frightened", color: "#b8b8b8" },
  { name: "Angry", color: "#d46a6a" },
  { name: "Furious", color: "#d46a6a" },
  { name: "Irritated", color: "#d46a6a" },
  { name: "Sad", color: "#8dbed8" },
  { name: "Depressed", color: "#8dbed8" },
  { name: "Lonely", color: "#8dbed8" },
  { name: "Betrayed", color: "#d46a6a" },
  { name: "Guilty", color: "#b8b8b8" },
  { name: "Ashamed", color: "#b8b8b8" },
  { name: "Helpless", color: "#8dbed8" },
];

export default emotionList;

// Hex Color Values:
// Red – #d46a6a
// Blue – #8dbed8
// Orange – #f38e4e
// Green – #aed581
// Gray – #b8b8b8
